import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="Header flex justify-between m-3">
          <Link href="/" className="text-2xl font-bold">
            SHOP
          </Link>
          <Link href="/cart">
            <button className="btn btn-green cursor-pointer">Cart</button>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
